### ISSUE TITLE
Don't use truly-scoped styles

### ISSUE THREAD

**Issue by weotch** [BKWLD/vue-modal#1]
So that the styles can be overridden on a project, I think you should use manual scoping rather than the `scoped` attribute.  Like [see how all the Vue-Visual styles](https://github.com/BKWLD/vue-visual/blob/master/index.vue#L121-L186) use the `vv-` prefix.  

Maybe use like `vue-modal-` ... or, for something shorter, maybe `bvm-`?  I don't like `vm` since that's a common term in Vue for "view model".

**Comment by mattaebersold** [comment]
I took care of this [here](https://github.com/BKWLD/vue-modal/blob/main/index.vue#:~:text=Latest%20commit-,2c8c1fd,-3%20minutes%20ago)
