### ISSUE TITLE
Rename to @bkwld/vue-modal

### ISSUE THREAD

**Issue by weotch** [BKWLD/vue-modal#2]
We'll want the package to be ultimately be called `@bkwld/vue-modal` since https://www.npmjs.com/package/vue-modal is already taken.  I do like the straightforward name rather than something product-y since it serves a straightforward purpose.

**Comment by mattaebersold** [comment]
![image](https://user-images.githubusercontent.com/435606/134942698-5d1c7ea6-8dff-4354-8df8-0f2589294762.png)

We should be good with just having it named here in `package.json` right?

**Comment by weotch** [comment]
I think so?  I think I may need to do the initial npm publish.  Any objection to me doing that now?

**Comment by mattaebersold** [comment]
ya let's do it

**Comment by weotch** [comment]
Btw, check out the `npm version` command for tagging new versions.  It both updates the package.json and creates a git tag.

https://bukwild.slab.com/posts/contributing-to-open-source-dd1k8e3g#releasing-changes

**Comment by weotch** [comment]
It also triggers these 2 version related commands when run:

https://github.com/BKWLD/vue-modal/blob/01f92c94533cd941741f5d234fcff34e2afe11af/package.json#L8-L9

**Comment by weotch** [comment]
Published! https://www.npmjs.com/package/@bkwld/vue-modal

**Comment by mattaebersold** [comment]
Yea I was looking at that earlier, and I removed the storybook part of the command locally, but hadn't pushed that yet. 

This is great!
